- name: Ping playbook
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: ping task
      ansible.builtin.ping:

    - name: pring msg
      ansible.builtin.debug:
        msg: Hello world
